version: "3"
services:
  profile:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - profile-mongodb
  profile-mongodb:
    image: mongo:3.6
    container_name: "profile-mongodb"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_USER="pass"